# Generated by Django 2.2.1 on 2019-06-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='address_zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='card_last_four',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='date_time',
            field=models.IntegerField(),
        ),
    ]
