# Generated by Django 2.2.1 on 2019-06-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190606_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstanding',
            name='code',
            field=models.IntegerField(),
        ),
    ]
