# Generated by Django 2.2.1 on 2019-06-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_paymenttransaction_input_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='origin',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Shipment'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='address_line_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipmenttypedetails',
            name='name',
            field=models.CharField(default='dry', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='card_last_four',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='arrival_actual',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='departure_actual',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
