# Generated by Django 2.2.1 on 2019-06-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190606_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='card_last_four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Shipment'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='arrival_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='departure_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
