# Generated by Django 2.2.1 on 2019-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190606_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='current_sequence',
            field=models.IntegerField(default=0),
        ),
    ]
