# Generated by Django 2.2.1 on 2019-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190607_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
