# Generated by Django 2.2.1 on 2019-06-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190607_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
