# Generated by Django 2.2.1 on 2019-06-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190607_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
