# Generated by Django 2.2.1 on 2019-06-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190607_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='billto_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_billto_contact', to='main_app.CustomerContact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='consignee_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_consignee_contact', to='main_app.CustomerContact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_shipper_contact', to='main_app.CustomerContact'),
            preserve_default=False,
        ),
    ]
