# Generated by Django 2.2.1 on 2019-06-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190608_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='billto_contact',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='consignee_contact',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipper_contact',
        ),
    ]
