# Generated by Django 2.2.1 on 2019-06-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20190609_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='no',
        ),
    ]
