# Generated by Django 2.2.1 on 2019-06-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_shipment_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='desc',
            field=models.CharField(default='filler', max_length=255),
            preserve_default=False,
        ),
    ]
