# Generated by Django 2.2.1 on 2019-06-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20190609_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='equipment',
            field=models.ForeignKey(default='NPCU200001', on_delete=django.db.models.deletion.CASCADE, to='main_app.Equipment'),
            preserve_default=False,
        ),
    ]
